name: shop_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  http: ^1.2.0    # <-- Naya package JSON fetch karne ke liye

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
